version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: enrico_cerrini_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5481:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/enrico_cerrini_dev
      - JWT_SECRET=your-jwt-secret-key-here
      - JWT_REFRESH_SECRET=your-refresh-secret-key-here
      - CORS_ORIGIN=http://localhost:3001
      - DEBUG=False
      - ENVIRONMENT=production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["./startup.sh"]

volumes:
  postgres_data:
