"""add_paid_amount_to_sales

Revision ID: 98502dc54697
Revises: 93094a61d293
Create Date: 2025-08-07 08:10:36.404815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98502dc54697'
down_revision: Union[str, None] = '93094a61d293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('paid_amount', sa.Numeric(10, 2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'paid_amount')
    # ### end Alembic commands ###
